// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwwxcWk6wrwTUqXaoZH_l8pwjfGqiHgOo',
    appId: '1:733760701436:web:44e625e408537d594a6879',
    messagingSenderId: '733760701436',
    projectId: 'reciclagemapp-dbe4f',
    authDomain: 'reciclagemapp-dbe4f.firebaseapp.com',
    storageBucket: 'reciclagemapp-dbe4f.firebasestorage.app',
    measurementId: 'G-B2VVCPM67T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFr_KZ3VZDBknopigqcTZ03XviKCpCp5Q',
    appId: '1:733760701436:android:c07f5b3bf38ad8cd4a6879',
    messagingSenderId: '733760701436',
    projectId: 'reciclagemapp-dbe4f',
    storageBucket: 'reciclagemapp-dbe4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyDL78WLOUicUmdPmRlkMvNpen25F826o',
    appId: '1:733760701436:ios:6e4570f21113ba744a6879',
    messagingSenderId: '733760701436',
    projectId: 'reciclagemapp-dbe4f',
    storageBucket: 'reciclagemapp-dbe4f.firebasestorage.app',
    iosBundleId: 'com.example.reciclagemApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyDL78WLOUicUmdPmRlkMvNpen25F826o',
    appId: '1:733760701436:ios:6e4570f21113ba744a6879',
    messagingSenderId: '733760701436',
    projectId: 'reciclagemapp-dbe4f',
    storageBucket: 'reciclagemapp-dbe4f.firebasestorage.app',
    iosBundleId: 'com.example.reciclagemApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwwxcWk6wrwTUqXaoZH_l8pwjfGqiHgOo',
    appId: '1:733760701436:web:8d0d0c1f867122a34a6879',
    messagingSenderId: '733760701436',
    projectId: 'reciclagemapp-dbe4f',
    authDomain: 'reciclagemapp-dbe4f.firebaseapp.com',
    storageBucket: 'reciclagemapp-dbe4f.firebasestorage.app',
    measurementId: 'G-9LW4XKZ1QR',
  );
}
