// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiWIH-rxW_vqicNjVys6TFrG-7KXv6mxA',
    appId: '1:510039772116:web:03ce29665a632edec1a441',
    messagingSenderId: '510039772116',
    projectId: 'greenpy-app',
    authDomain: 'greenpy-app.firebaseapp.com',
    storageBucket: 'greenpy-app.firebasestorage.app',
    measurementId: 'G-6X1PL0979K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe9W81iAYrsUySY_qLqhk5WArZ_hkVeL4',
    appId: '1:510039772116:android:77bda6787d2a35e4c1a441',
    messagingSenderId: '510039772116',
    projectId: 'greenpy-app',
    storageBucket: 'greenpy-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApTcrb0fTe6UPJGP2xybDuIvDgId8u250',
    appId: '1:510039772116:ios:cb5bdd7fc57c29e8c1a441',
    messagingSenderId: '510039772116',
    projectId: 'greenpy-app',
    storageBucket: 'greenpy-app.firebasestorage.app',
    iosClientId: '510039772116-e2mt6jjci0rbkt4qq08vu72u9og2tntg.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenpy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApTcrb0fTe6UPJGP2xybDuIvDgId8u250',
    appId: '1:510039772116:ios:cb5bdd7fc57c29e8c1a441',
    messagingSenderId: '510039772116',
    projectId: 'greenpy-app',
    storageBucket: 'greenpy-app.firebasestorage.app',
    iosClientId: '510039772116-e2mt6jjci0rbkt4qq08vu72u9og2tntg.apps.googleusercontent.com',
    iosBundleId: 'com.example.greenpy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiWIH-rxW_vqicNjVys6TFrG-7KXv6mxA',
    appId: '1:510039772116:web:5dae2d5e76bb4b5dc1a441',
    messagingSenderId: '510039772116',
    projectId: 'greenpy-app',
    authDomain: 'greenpy-app.firebaseapp.com',
    storageBucket: 'greenpy-app.firebasestorage.app',
    measurementId: 'G-QCR2KX3SYX',
  );

}